name: Deploy Package to NuGet
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      build_preview:
        description: 'Preview Build?'
        required: true
        type: boolean

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest

    env:
      MajorVersion: 0
      MinorVersion: 1
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: version
      run: echo "::set-output name=date::$(date +'%Y%m.%d')"

    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      run: echo "Branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      run: echo "Branch=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Set Version Prefix
      env:
        VERPREF: ${{ format('{0}.{1}.{2}{3}', env.MajorVersion, env.MinorVersion, steps.date.outputs.date, github.run_number) }}
      run: echo "VersionPrefix=$(echo ${VERPREF})" >> $GITHUB_ENV

    - name: Set Version Suffix
      if: ${{ inputs.build_preview }} 
      run: echo "VersionSuffix=Preview" >> $GITHUB_ENV
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Build Project
      run: dotnet pack ./src/Stebet.Nats.DistributedCache/Stebet.Nats.DistributedCache.csproj --configuration Release

    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./src/Stebet.Nats.DistributedCache/nupkg/*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
