name: Build & Test

on: [push]
jobs:
  build:
    services:
      nats:
        image: stebet/nats-js:latest
        ports:
          - 4222:4222
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-build